nelmio_api_doc:
    documentation:
        info:
            title: Articles API app
            description: API for articles-platform!
            version: 1.0.0
#    areas: # to filter documented areas
#        path_patterns:
#            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    areas:
        path_patterns: # an array of regexps (document only routes under /api, expect /api/doc)
#            - ^/api(?!/doc$)
            - ^/api(\/(healthcheck|register)$)
        host_patterns: # document only routes with a host of the form api.*
#            - ^api\.
