#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

app.swagger_ui:
  path: /api/doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

#app.swagger:
#  path: /api/doc.json
#  methods: GET
#  defaults: { _controller: nelmio_api_doc.controller.swagger }

index:
  path: /
  controller: App\Controller\DefaultController::index
  methods: GET
healthcheck:
  path: /api/healthcheck
  controller: App\Controller\SystemController::healthcheck
  methods: GET
